
apply plugin: 'eclipse'

eclipse {
    project {
        name = "Dynmap(DynmapCoreAPI)"
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

description = "DynmapCoreAPI"

jar {
    destinationDirectory = file '../target'
}

artifacts {
    archives jar
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}
